### ISSUE TITLE
unescaped characters in the tmLanguage file?

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/EditorSyntax#139]
I've noticed when generating the tmLanguage file programmatically, that I end up with more characters escaped, namely `&quot;` and `&apos;`, than are escaped in the file in the repository.  I couldn't seem to find any guidance on this.

repository
```
<key>match</key>
<string>\b((?:\'|\")?)(\w+)((?:\'|\")?)(?:\s+)?(=)(?:\s+)?</string>
```

programmatically generated
```
<key>match</key>
<string>\b((?:\&apos;|\&quot;)?)(\w+)((?:\&apos;|\&quot;)?)(?:\s+)?(=)(?:\s+)?</string>
```
Any guidance here?

**Comment by omniomi** [comment]
How was that generated? The plist format does not require characters like quotes be converted to SGML entities. Only the `<` and `>` symbols need to be converted to `&lt;` and `&gt;`. That said, I do not know if using entities elsewhere would actually break anything... What happens if you convert it back using the build script?

**Comment by msftrncs** [comment]
@omniomi , I wrote a function to convert the JSON tmLanguage file, and used `[System.Security.SecurityElement]::Escape()` which just escapes all 5 characters.  However, according to [StackOverflow](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents) and to [w3.org](https://www.w3.org/TR/xml/#syntax) that's not exactly what should be done, depending on were the contents are going, as there are some places they are not to be escaped.  Even `>` doesn't need to be escaped in the character data. (Kinda like the rules for regex character class groups)
