### ISSUE TITLE
Syntax highlighting getting worse?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/EditorSyntax#16]
What is going on with this project?
Have we completely lost the ability to detect regressions?

``` posh
$Whatever.Name -match "Id"
```

![2016-07-28 12_08_17- untitled-1 - amsautomation - visual studio code](https://cloud.githubusercontent.com/assets/192942/17220098/0f2bfbbc-54bc-11e6-8227-ef2308582888.png)

``` posh
$Whatever.Name -match ".*Id"
```

![2016-07-28 12_09_58- untitled-1 - amsautomation - visual studio code](https://cloud.githubusercontent.com/assets/192942/17220204/453d7122-54bc-11e6-8251-987a9b0ae213.png)

This isn't acceptable.

**Comment by gravejester** [comment]
The problem with detecting regressions in a project like this, is that it will never be any better than the test scripts we test the changes against. When we pushed these changes everything was fine when tested against the test scripts. So really, these kinds of feedback is really important, and we need to get them added to the test script as well.

This particular issue, and really a bunch of similar issues that have been reported I think is because I tried to match variables with properties, like in your example. This turns out to be a lot harder to do correctly than I initially thought, so I'm going to disable this bit, which should "fix" a lot of the issues we are now seeing.

I apologize for not testing this better before pushing this particular "feature".

**Comment by Jaykul** [comment]
Well, the *real* problem is that there's nothing automated set up, so we're relying on visual inspections of code highlighting, and you don't have any test results you can throw in my face to say "hey dude, the tests passed, write better tests if you don't like it!" 😉 

But yeah. I want something like the new sublime text test harness ;-)

https://www.sublimetext.com/docs/3/syntax.html#testing

**Comment by gravejester** [comment]
Oh. yeah, something like that would be great. I know the VSCode team try to do something automated, but it's a mess, hard-coded color codes etc. Would definitely have been cool to have something that would do the testing for us. When we get all the issues sorted out perhaps I'll have the time to look into something. Would be nice to be able to use Pester :)

**Comment by omniomi** [comment]
The two issues in the top comment are resolved. Regression is now checked for by [atom-grammar-test](https://github.com/kevinastone/atom-grammar-test) and Jasmine.\

There are a total of 359 tests with 3459 assertions.
