### ISSUE TITLE
Dollar sign '$' should be included as part of the variable token

### ISSUE THREAD

**Issue by daviwil** [PowerShell/EditorSyntax#23]
The dollar sign `$` should be included as part of the variable token because editors like VS Code use the syntax tokens to determine what text to select when the user double-clicks in the current file.  Currently if the user double-clicks in a variable like `$myVar`, only the `myVar` portion will be selected since the `$` is treated as a separate symbol.

**Comment by daviwil** [comment]
Originally filed by @deshiknaves with issue https://github.com/PowerShell/vscode-powershell/issues/240.

**Comment by MacKopes1** [comment]
I would like this fixed as well. Curious if there is any progress/status on it.

**Comment by SillyCode** [comment]
Would very much like this too

**Comment by gravejester** [comment]
Are we sure this is what we really want? Some of the guides I have seen regarding scope names suggests that the $ should be scoped as **punctuation.definition.variable** I tried a test where I renamed this scope to **variable.punctuation** as this would mean that both the $ and the variable name have the same root scope. Double-clicking in vscode still only highlighted the variable name.

I then tried to apply a **meta.variable** scope to the whole token ($ as well as the variable name), with the same results.

Checking in ISE this is the exact same behaviour I see there. The name of the variable is highlighted on double-click, not the $.

**Comment by MacKopes1** [comment]
Yep, you are correct that this is the same behavior as in PowerShell ISE (which is ALSO terrible behavior). I STILL default to using the very old PowerShell GUI Editor because it DOES have the correct behavior of including the $ when double clicking. It's a huge burden on speed to not be able to quickly copy and paste variables including the $

**Comment by gravejester** [comment]
My only concern is that it won't work even if we scope the $ the same as the variable name. @daviwil do you know for certain that the editor is using the scope names for this? If not, is there any other way we can achieve this? Perhaps as a setting so that people can choose if they want this behavior or not?

**Comment by gravejester** [comment]
As mentioned above, adding the following to the settings works:

    "[powershell]": {
        "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
    }

**Comment by daviwil** [comment]
@gravejester hmmm...  If this is driven by `editor.wordSeparators`, then maybe the syntax def has nothing to do with it.  Let me see if there's some way I can make this happen via the PS extension.

**Comment by daviwil** [comment]
Filed an issue with the VS Code team to see if there's a way I can override that setting.

Also just found [this issue](https://github.com/PowerShell/vscode-powershell/issues/858) at the vscode-PowerShell repo where someone also asked for the dollar sign to be colored the same as the variable name.

**Comment by gravejester** [comment]
Yeah, I have mixed feelings about that. In the grammar I'm much more concerned with the tokens getting "proper" scope names, and leave it up the the different themes how these should be colored. I'd rather not cheat by using the wrong scope names just so that a token can get a particular color in the default theme. Thoughts?

**Comment by daviwil** [comment]
Sounds fine to me to have accurate tokens. The ISE theme can color the token consistently with the ISE :)

**Comment by omniomi** [comment]
Closing as the discussion appears to have reached a conclusions and an issue was opened for VS Code. @gravejester is also correct about `punctuation.definition.variable`. See: https://www.sublimetext.com/docs/3/scope_naming.html#variable

We can add this as a line item when we review scopes in general if someone wants to make a case for breaking convention.

**Comment by vors** [comment]
@lzybkr made a case in https://github.com/SublimeText/PowerShell/issues/147

> The default coloring of variables in VSCode is hard to read because the sigil is colored, but not the variable name. This puts too much emphasis on the sigil and not the name.
> 
> I prefer having the sigil+variable colored, but not coloring anything would be better than the default.
> 
> Here is an example:
> 

![image](https://cloud.githubusercontent.com/assets/2148248/13186115/59a17c76-d6f9-11e5-9e3e-8be2c22e193f.png)

**Comment by vors** [comment]
How does the double-click select behave with overlap?

I like the proposition so far, but it would be awesome to see it visually with 1 or more default themes.
