### ISSUE TITLE
Double click highlighting Enhancement

### ISSUE THREAD

**Issue by jbruns2015** [PowerShell/EditorSyntax#53]
In PowerGUI tool, if i double clicked on $a for instance, it would highlight not only the 'a' but also the '$'.

Update your editor to do the same.

**Comment by omniomi** [comment]
Hi @jbruns2015, this repository is for issues with syntax highlighting. This behaviour would be controlled either by Microsoft/vscode or PowerShell/vscode-powershell. That said it appears to highlight the whole thing now so perhaps this was changed at some point since this was opened:

![highlight](https://user-images.githubusercontent.com/12937335/40327140-14ba3394-5cff-11e8-871e-91768b1af29b.png)
