### ISSUE TITLE
Regex in ValidatePattern breaks highlighting

### ISSUE THREAD

**Issue by AurimasNav** [PowerShell/EditorSyntax#98]
### Environment

- Editor and Version (VS Code, Atom, Sublime): VS Code 1.23.1
- Your primary theme: Dark+ (default dark)

### Issue Description
Having round and square bracket combination within parameter validation breaks highlighting

#### Screenshots
expected:
![image](https://user-images.githubusercontent.com/7810047/40467270-e275a3c0-5f31-11e8-92b0-2108860ade77.png)

erronous:
![image](https://user-images.githubusercontent.com/7810047/40467339-2e4d793a-5f32-11e8-8ac5-21302133e0d8.png)

### Code Samples
```PowerShell
class MyClass
{
    [ValidatePattern('^(test)[a-z]')]
    [string]$Prop1
    [string]$prop2

    MyClass([string]$string)
    {
        $this.Prop1 = $string
    }
}
```

**Comment by omniomi** [comment]
Hi @AurimasNav,

This is fixed in the most recent version. The changes are live in VS Code Insiders (https://code.visualstudio.com/insiders/) as of this morning and should appear in the standard version in the next release.

If you would like to install the latest version of the syntax now without using the Insiders version of VS Code you can download the latest json file here: https://ci.appveyor.com/api/buildjobs/t6f8dy8nsrt8w3ob/artifacts/powershell.tmLanguage.json and replace the one in `<vs code install dir>\resources\app\extensions\powershell\syntaxes`
